Import the dataset and setup git

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("clmentbisaillon/fake-and-real-news-dataset")

print("Path to dataset files:", path)

/Users/amanganglani/.pyenv/versions/3.13.0/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: /Users/amanganglani/.cache/kagglehub/datasets/clmentbisaillon/fake-and-real-news-dataset/versions/1

In [3]:
import os

# List the contents of the downloaded dataset directory
dataset_files = os.listdir(path)
print(f"Files in the dataset directory '{path}':\n{dataset_files}")

Files in the dataset directory '/Users/amanganglani/.cache/kagglehub/datasets/clmentbisaillon/fake-and-real-news-dataset/versions/1':
['Fake.csv', 'True.csv']

Visualize the dataset

In [4]:
import pandas as pd

true_news_df = pd.read_csv(os.path.join(path, 'True.csv'))
fake_news_df = pd.read_csv(os.path.join(path, 'Fake.csv'))

print("First 5 rows of True News dataset:")
display(true_news_df.head())

print("\nFirst 5 rows of Fake News dataset:")
display(fake_news_df.head())

First 5 rows of True News dataset:

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

First 5 rows of Fake News dataset:

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [8]:

# Add 'truth' column to true_news_df with value 1
true_news_df['truth'] = 1

# Add 'truth' column to fake_news_df with value 0
fake_news_df['truth'] = 0

# Combine the dataframes
combined_df = pd.concat([true_news_df, fake_news_df], ignore_index=True)

print("Combined DataFrame head:")
display(combined_df.head())

print("\nCombined DataFrame tail:")
display(combined_df.tail())

print(f"\nShape of combined DataFrame: {combined_df.shape}")
print(f"Number of true news entries: {combined_df[combined_df['truth'] == 1].shape[0]}")
print(f"Number of fake news entries: {combined_df[combined_df['truth'] == 0].shape[0]}")

Combined DataFrame head:

,title,text,subject,date,truth
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

Combined DataFrame tail:

,title,text,subject,date,truth
44893,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",0
44894,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",0
44895,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",0
44896,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",0
44897,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",0

Shape of combined DataFrame: (44898, 5)
Number of true news entries: 21417
Number of fake news entries: 23481