Import the dataset and setup git

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("clmentbisaillon/fake-and-real-news-dataset")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/clmentbisaillon/fake-and-real-news-dataset?dataset_version_number=1...

100%|██████████| 41.0M/41.0M [00:00<00:00, 164MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/clmentbisaillon/fake-and-real-news-dataset/versions/1

In [2]:
import os

# List the contents of the downloaded dataset directory
dataset_files = os.listdir(path)
print(f"Files in the dataset directory '{path}':\n{dataset_files}")

Files in the dataset directory '/root/.cache/kagglehub/datasets/clmentbisaillon/fake-and-real-news-dataset/versions/1':
['True.csv', 'Fake.csv']

In [6]:
!git clone https://github.com/amangang3/HODL

Cloning into 'HODL'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (6/6), done.

In [9]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

### 1. Initialize Git and Clone your Repository (if you haven't already)

If you've already saved your notebook to GitHub, it means you likely have a local copy (even if it's in the Colab environment) that's connected to a remote GitHub repository. If you started a brand new Colab notebook and want to connect it to an existing GitHub repository, you'd typically clone it first. Make sure to replace `YOUR_GITHUB_USERNAME` and `YOUR_REPOSITORY_NAME` with your actual details.

In [ ]:
# This step is usually done once if you're starting with an empty Colab
# If you've already opened a notebook from GitHub, you might be in the repo's directory.
# Use %cd to navigate into your repository's folder if it's not the current working directory.
# !git clone https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPOSITORY_NAME.git
# %cd YOUR_REPOSITORY_NAME

### 2. Check the Status of your Repository

Before committing, it's good practice to see what changes you've made. This command shows modified files that are not yet staged for commit.

In [ ]:
!git status

### 3. Stage your Changes

This command adds all current changes to the staging area, preparing them for the commit. If you only want to stage specific files, replace the `.` with the file path (e.g., `!git add my_notebook.ipynb`).

In [ ]:
!git add .

### 4. Commit your Changes

Now, you'll commit the staged changes to your local repository. The `-m` flag is for your commit message, which should briefly describe the changes you've made. Replace `"Descriptive commit message"` with your actual message.

In [ ]:
!git commit -m "Descriptive commit message"

### 5. Push your Changes to GitHub

Finally, push your committed changes from your local Colab repository to the remote GitHub repository. You might be prompted to enter your GitHub username and personal access token (PAT) if you haven't configured credential caching.

In [ ]:
# You might need to set up your global user name and email first:
# !git config --global user.email "your_email@example.com"
# !git config --global user.name "Your Name"

!git push origin main # or 'master' depending on your branch name

Visualize the dataset

In [3]:
import pandas as pd

true_news_df = pd.read_csv(os.path.join(path, 'True.csv'))
fake_news_df = pd.read_csv(os.path.join(path, 'Fake.csv'))

print("First 5 rows of True News dataset:")
display(true_news_df.head())

print("\nFirst 5 rows of Fake News dataset:")
display(fake_news_df.head())

First 5 rows of True News dataset:

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

First 5 rows of Fake News dataset:

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [11]:
import pandas as pd

# Add 'truth' column to true_news_df with value 1
true_news_df['truth'] = 1

# Add 'truth' column to fake_news_df with value 0
fake_news_df['truth'] = 0

# Combine the dataframes
combined_df = pd.concat([true_news_df, fake_news_df], ignore_index=True)

print("Combined DataFrame head:")
display(combined_df.head())

print("\nCombined DataFrame tail:")
display(combined_df.tail())

print(f"\nShape of combined DataFrame: {combined_df.shape}")
print(f"Number of true news entries: {combined_df[combined_df['truth'] == 1].shape[0]}")
print(f"Number of fake news entries: {combined_df[combined_df['truth'] == 0].shape[0]}")

Combined DataFrame head:

,title,text,subject,date,truth
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

Combined DataFrame tail:

,title,text,subject,date,truth
44893,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",0
44894,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",0
44895,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",0
44896,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",0
44897,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",0

Shape of combined DataFrame: (44898, 5)
Number of true news entries: 21417
Number of fake news entries: 23481

In [21]:
!git config --global user.email "amangang3@gmail.com"
!git config --global user.name "amangang3"

In [24]:
# First, navigate into your repository directory
%cd /content/HODL/

# Check the status to see what Git knows about EDA.ipynb
!git status

# Now, add your notebook (or all changes with .)
!git add EDA.ipynb

# Commit your changes
!git commit -m "EDA"

# Push your changes to GitHub (you might need to handle authentication here)
!git push origin main

# Optionally, change back to the root content directory if needed
# %cd /content/

/content/HODL
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
fatal: could not read Username for 'https://github.com': No such device or address